-- Generated by scripts/gen-seed-sql.ts from src/lib/seed/fixture.ts. Do not edit by hand.
begin;
insert into orgs (id, name, short_name, slug) values ('73cc980e-73b1-45ae-aec6-77a2a513adec', 'Northlight Media', 'Northlight', 'northlight');
insert into accounts (id, org_id, name, short_name, logo_url) values ('2231160b-8311-44f0-a2e4-93ee28681967', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Lumen Interactive · Arcadia', 'Arcadia', '/logos/arcadia.svg');
insert into deals (id, org_id, account_id, name, stage, value_amount, value_currency) values ('b4efc243-1b14-414e-a36f-26a6d3ed2658', '73cc980e-73b1-45ae-aec6-77a2a513adec', '2231160b-8311-44f0-a2e4-93ee28681967', 'Summer Creator Package', 'revisions', 120000, 'USD');
insert into deal_briefs (deal_id, budget_amount, budget_currency, audience, platforms, flight_start, flight_end, deliverables, measurement) values ('b4efc243-1b14-414e-a36f-26a6d3ed2658', 130000, 'USD', '18–34 gamers', array['Twitch', 'YouTube']::text[], '2027-06-01', '2027-08-31', array['Two tentpole livestreams', 'Sponsored sessions', 'Short-form cutdowns', 'Community posts and codes']::text[], array['View-through', 'Qualified sentiment', 'Arcadia Pass trial sign-ups']::text[]);
insert into people (id, org_id, name, email, title, side, avatar_color) values ('38c01502-185e-4fa5-a2e8-5a340938324e', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Alex Romero', 'alex@lumen.example', 'Brand manager', 'buyer', '#7c8b6f');
insert into people (id, org_id, name, email, title, side, avatar_color) values ('36eb0377-0ada-4ac6-ae6f-2843a6138418', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Kim Lee', 'kim@lumen.example', 'Media lead', 'buyer', '#a08a9a');
insert into people (id, org_id, name, email, title, side, avatar_color) values ('e191ecfd-37fe-4c85-ac58-a5e8f93471ce', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Sam Patel', 'sam@lumen.example', 'Agency planner', 'buyer', '#8f8a7c');
insert into people (id, org_id, name, email, title, side, avatar_color) values ('c7d101c1-c7ef-499e-aad1-8119d32954ec', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Maya Chen', 'maya@northlight.example', 'Sales lead', 'seller', '#8a7f73');
insert into people (id, org_id, name, email, title, side, avatar_color) values ('23d902de-defe-46ba-ab91-8dc99bf95eea', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Jordan Ali', 'jordan@northlight.example', 'Strategy', 'seller', '#c07a4f');
insert into people (id, org_id, name, email, title, side, avatar_color) values ('e23aa548-5adf-46af-afbc-62e82882aadc', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'Priya Rao', 'priya@northlight.example', 'Measurement', 'seller', '#6f8a9a');
insert into spaces (id, org_id, deal_id, initiator, status_label, status_due_date, buyer_lead_id, seller_lead_id, suggested_questions) values ('7f82b744-7a58-45fc-a9ec-a31812007c15', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'seller', 'Awaiting your feedback', '2026-10-06', '38c01502-185e-4fa5-a2e8-5a340938324e', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', array['What changed in v3?', 'Show the creator breakdown', 'What''s the measurement plan?']::text[]);
insert into space_links (id, space_id, token_hash) values ('0d867547-7c80-4974-a015-8df042987bb7', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'c4ea6b4220134653422109f93d3a2e54b643d71d19c16ff2975b69e446a60aa6');
insert into memberships (id, org_id, person_id, scope, account_id, deal_id, side, invited_at, last_seen_at) values ('b3dec3f1-dc81-40d2-a922-38f8eed103b3', '73cc980e-73b1-45ae-aec6-77a2a513adec', '38c01502-185e-4fa5-a2e8-5a340938324e', 'deal', null, 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'buyer', '2026-08-26T12:00:00Z', null);
insert into memberships (id, org_id, person_id, scope, account_id, deal_id, side, invited_at, last_seen_at) values ('666cdf5b-0c0d-4977-abd0-5c8dae1cabbb', '73cc980e-73b1-45ae-aec6-77a2a513adec', '36eb0377-0ada-4ac6-ae6f-2843a6138418', 'deal', null, 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'buyer', '2026-08-26T12:00:00Z', '2026-09-30T12:00:00Z');
insert into memberships (id, org_id, person_id, scope, account_id, deal_id, side, invited_at, last_seen_at) values ('5a5bbd2e-ffd8-4ee0-a73d-809ff4fd42e6', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'e191ecfd-37fe-4c85-ac58-a5e8f93471ce', 'deal', null, 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'buyer', '2026-09-30T12:00:00Z', null);
insert into memberships (id, org_id, person_id, scope, account_id, deal_id, side, invited_at, last_seen_at) values ('60ebccb5-cdcb-48c5-a3ee-4b535a228fb3', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', 'deal', null, 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'seller', '2026-08-26T12:00:00Z', null);
insert into memberships (id, org_id, person_id, scope, account_id, deal_id, side, invited_at, last_seen_at) values ('ffb89385-d12a-4f27-a7b0-1c14ce2fe6a9', '73cc980e-73b1-45ae-aec6-77a2a513adec', '23d902de-defe-46ba-ab91-8dc99bf95eea', 'deal', null, 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'seller', '2026-08-26T12:00:00Z', '2026-09-29T12:00:00Z');
insert into memberships (id, org_id, person_id, scope, account_id, deal_id, side, invited_at, last_seen_at) values ('1d39528e-0da5-4b9c-a290-4f60d9973472', '73cc980e-73b1-45ae-aec6-77a2a513adec', 'e23aa548-5adf-46af-afbc-62e82882aadc', 'deal', null, 'b4efc243-1b14-414e-a36f-26a6d3ed2658', 'seller', '2026-08-26T12:00:00Z', '2026-09-26T12:00:00Z');
insert into documents (id, space_id, title, kind, source, pinned, position) values ('2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'Summer Creator Proposal', 'doc', 'google_drive', false, 0);
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('806155a3-dbf8-460a-a937-9194d150c388', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 1, '2026-09-09T12:00:00Z', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', 'Fourteen creators across three tiers over a two-month flight, $128K.', true, 'Overview

Fourteen creators across three tiers over a two-month flight.

Pricing

Total investment $128,000.');
insert into document_sections (id, version_id, number, heading, body) values ('dc0f3240-bc09-4312-a769-c4218ee91c85', '806155a3-dbf8-460a-a937-9194d150c388', 1, 'Overview', 'Fourteen creators across three tiers over a two-month flight.');
insert into document_sections (id, version_id, number, heading, body) values ('61e4b521-8410-4fdb-a639-19f395b4c8ed', '806155a3-dbf8-460a-a937-9194d150c388', 2, 'Pricing', 'Total investment $128,000.');
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('aa92c790-166b-4f02-a1a3-f4f08fe92595', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 2, '2026-09-15T12:00:00Z', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', 'Thirteen creators across three tiers over June and July, $124K.', true, 'Overview

Thirteen creators across three tiers, June and July.

Creator roster

Tier 1: four creators. Tier 2: five creators. Tier 3: four creators.

Pricing

Total investment $124,000.');
insert into document_sections (id, version_id, number, heading, body) values ('17f14d3c-59dd-49d8-ac9d-b5caf5656663', 'aa92c790-166b-4f02-a1a3-f4f08fe92595', 1, 'Overview', 'Thirteen creators across three tiers, June and July.');
insert into document_sections (id, version_id, number, heading, body) values ('ecd7cc97-1eff-415e-a43a-bee9b40a1532', 'aa92c790-166b-4f02-a1a3-f4f08fe92595', 2, 'Creator roster', 'Tier 1: four creators. Tier 2: five creators. Tier 3: four creators.');
insert into document_sections (id, version_id, number, heading, body) values ('c7387ff3-ede1-4a2b-afc8-60cdd00b3102', 'aa92c790-166b-4f02-a1a3-f4f08fe92595', 3, 'Pricing', 'Total investment $124,000.');
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('556fcb13-e426-43ba-ae59-dc4c85a1b724', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 3, '2026-09-22T12:00:00Z', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', 'Twelve creators across three tiers, June to August, anchored by two tentpole streams.', true, 'Overview

Twelve creators across three tiers deliver a three-month presence on Twitch and YouTube, anchored by two tentpole livestreams aligned to Arcadia Pass summer drops.

Creator roster

Tier 1: three creators with dedicated streams and integrated segments. Tier 2: five creators running sponsored sessions plus short-form cutdowns. Tier 3: four creators providing community posts and codes.

Pricing

Tier 1 $54,000. Tier 2 $42,000. Tier 3 $14,000. Production and reporting $10,000. Total $120,000.

Payment terms: 50% on signature, 50% on completion of the August flight.

Flight plan

June launches the roster with a Tier 1 tentpole stream. July sustains weekly sponsored sessions. August closes with the second tentpole and a community recap.

Creative approvals run on a 48-hour turnaround with Arcadia brand marketing.');
insert into document_sections (id, version_id, number, heading, body) values ('6ca4b9bf-7da2-4f2a-a5ca-17e10ac355e5', '556fcb13-e426-43ba-ae59-dc4c85a1b724', 1, 'Overview', 'Twelve creators across three tiers deliver a three-month presence on Twitch and YouTube, anchored by two tentpole livestreams aligned to Arcadia Pass summer drops.');
insert into document_sections (id, version_id, number, heading, body) values ('7790cccc-0556-4ec1-a90e-6a2fbf22e67f', '556fcb13-e426-43ba-ae59-dc4c85a1b724', 2, 'Creator roster', 'Tier 1: three creators with dedicated streams and integrated segments. Tier 2: five creators running sponsored sessions plus short-form cutdowns. Tier 3: four creators providing community posts and codes.');
insert into document_sections (id, version_id, number, heading, body) values ('197c4908-4c5f-4467-a22e-9a768745c670', '556fcb13-e426-43ba-ae59-dc4c85a1b724', 3, 'Pricing', 'Tier 1 $54,000. Tier 2 $42,000. Tier 3 $14,000. Production and reporting $10,000. Total $120,000.

Payment terms: 50% on signature, 50% on completion of the August flight.');
insert into document_sections (id, version_id, number, heading, body) values ('c190d5e7-41e7-4237-a20b-b9bc12ff1015', '556fcb13-e426-43ba-ae59-dc4c85a1b724', 4, 'Flight plan', 'June launches the roster with a Tier 1 tentpole stream. July sustains weekly sponsored sessions. August closes with the second tentpole and a community recap.

Creative approvals run on a 48-hour turnaround with Arcadia brand marketing.');
insert into documents (id, space_id, title, kind, source, pinned, position) values ('403f455b-fc81-4eb3-a000-e59422a4d94b', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'Walkthrough Deck', 'slides', 'google_drive', false, 1);
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('1a267b21-290a-4064-a9a4-0d8393dab465', '403f455b-fc81-4eb3-a000-e59422a4d94b', 1, '2026-09-25T12:00:00Z', '23d902de-defe-46ba-ab91-8dc99bf95eea', 'Slides from the September 25 call: tiers, roster, and measurement.', true, 'Agenda

Package tiers, creator roster, measurement approach, next steps.

Next steps

Arcadia to share feedback on tiers by October 6.');
insert into document_sections (id, version_id, number, heading, body) values ('3fc6a453-8b26-4cc5-ae0d-e5da2dd690ed', '1a267b21-290a-4064-a9a4-0d8393dab465', 1, 'Agenda', 'Package tiers, creator roster, measurement approach, next steps.');
insert into document_sections (id, version_id, number, heading, body) values ('a58d6574-8b08-4058-a328-91fa46fee368', '1a267b21-290a-4064-a9a4-0d8393dab465', 2, 'Next steps', 'Arcadia to share feedback on tiers by October 6.');
insert into documents (id, space_id, title, kind, source, pinned, position) values ('0871ee31-b137-422f-a3fe-34973e716340', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'Creator Shortlist', 'sheet', 'google_drive', false, 2);
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('517d0648-29c5-4619-aca3-82008dd74c74', '0871ee31-b137-422f-a3fe-34973e716340', 1, '2026-09-12T12:00:00Z', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', 'Eighteen candidates under review across Twitch and YouTube.', true, 'Shortlist

Eighteen candidates under review across Twitch and YouTube.');
insert into document_sections (id, version_id, number, heading, body) values ('963f1fd4-e2dd-4185-a957-27f5de6a1e07', '517d0648-29c5-4619-aca3-82008dd74c74', 1, 'Shortlist', 'Eighteen candidates under review across Twitch and YouTube.');
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('23ccbf6e-7f9e-4044-a8a7-329ab3bd190f', '0871ee31-b137-422f-a3fe-34973e716340', 2, '2026-09-22T12:00:00Z', 'c7d101c1-c7ef-499e-aad1-8119d32954ec', 'The twelve selected creators with audience fit, reach, and alternates.', true, 'Selection

Twelve creators selected from eighteen reviewed, grouped by reach and format.

Alternates

Two alternates are held per tier in case of availability conflicts in June.');
insert into document_sections (id, version_id, number, heading, body) values ('b1bbe38c-09b9-4a10-a109-d27ebfb98e29', '23ccbf6e-7f9e-4044-a8a7-329ab3bd190f', 1, 'Selection', 'Twelve creators selected from eighteen reviewed, grouped by reach and format.');
insert into document_sections (id, version_id, number, heading, body) values ('1097dc79-bdea-40c9-a216-40a0501d7cd1', '23ccbf6e-7f9e-4044-a8a7-329ab3bd190f', 2, 'Alternates', 'Two alternates are held per tier in case of availability conflicts in June.');
insert into documents (id, space_id, title, kind, source, pinned, position) values ('abd31b4d-e2a1-4593-a3e6-84080f4aee78', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'Measurement Plan', 'doc', 'google_drive', false, 3);
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('e5e1b0cd-c75e-421d-aac6-b87afe84bc48', 'abd31b4d-e2a1-4593-a3e6-84080f4aee78', 1, '2026-09-26T12:00:00Z', 'e23aa548-5adf-46af-afbc-62e82882aadc', 'How reach, sentiment, and Arcadia Pass trials are tracked and reported.', true, 'Metrics

View-through, qualified sentiment, and Arcadia Pass trial sign-ups via creator codes.

Reporting

Monthly reports during the flight and a wrap report two weeks after close.');
insert into document_sections (id, version_id, number, heading, body) values ('0284b132-39bc-4ded-a8ee-f3ced6460c8a', 'e5e1b0cd-c75e-421d-aac6-b87afe84bc48', 1, 'Metrics', 'View-through, qualified sentiment, and Arcadia Pass trial sign-ups via creator codes.');
insert into document_sections (id, version_id, number, heading, body) values ('297d18a5-2104-46bc-a857-521e6f62524e', 'e5e1b0cd-c75e-421d-aac6-b87afe84bc48', 2, 'Reporting', 'Monthly reports during the flight and a wrap report two weeks after close.');
insert into documents (id, space_id, title, kind, source, pinned, position) values ('b538da8e-450c-4b69-a661-58b82b64dd17', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'Summer Brief', 'doc', 'google_drive', true, 4);
insert into document_versions (id, document_id, number, committed_at, shared_by, summary, shared, extracted_text) values ('e39c7d39-bf4b-4438-a415-ce9e317288fc', 'b538da8e-450c-4b69-a661-58b82b64dd17', 1, '2026-09-02T12:00:00Z', '38c01502-185e-4fa5-a2e8-5a340938324e', 'Your original brief: 18–34 gamers on Twitch and YouTube, $100–130K.', true, 'Objective

Cultural reach among 18–34 gamers for the Arcadia Pass summer lineup.

Budget

$100,000–130,000 inclusive of fees, production, and reporting.');
insert into document_sections (id, version_id, number, heading, body) values ('8b7d1a25-c3b6-4915-a5eb-fdb3ff14a6c5', 'e39c7d39-bf4b-4438-a415-ce9e317288fc', 1, 'Objective', 'Cultural reach among 18–34 gamers for the Arcadia Pass summer lineup.');
insert into document_sections (id, version_id, number, heading, body) values ('1f3174c1-3d4d-40c1-a96a-dae8ff9fcd63', 'e39c7d39-bf4b-4438-a415-ce9e317288fc', 2, 'Budget', '$100,000–130,000 inclusive of fees, production, and reporting.');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('7d1038d4-724d-47b3-a846-07a2a431e7ec', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'email', '2026-08-26T12:00:00Z', 'Initial outreach', 'Email');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('aa994a19-2e42-4907-a82a-31daf06afdd9', '7d1038d4-724d-47b3-a846-07a2a431e7ec', null, 0, 'asked', 'Creator program pitched for the Arcadia Pass summer');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('fa6e1eb9-4eef-4696-acac-67dc64e24804', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'document', '2026-09-02T12:00:00Z', 'RFP and brief received', 'Document');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('cfc0e964-0c40-4230-a1e1-2c830c5634f3', 'fa6e1eb9-4eef-4696-acac-67dc64e24804', 'b538da8e-450c-4b69-a661-58b82b64dd17', 0, 'new', 'Brief shared by Alex Romero');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('1252de35-c770-4bb4-ad6e-495f5c48cff2', 'fa6e1eb9-4eef-4696-acac-67dc64e24804', 'b538da8e-450c-4b69-a661-58b82b64dd17', 1, 'decided', '18–34 gamers on Twitch and YouTube');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('67869aec-9d55-4242-a4bf-db8f6a453c27', 'fa6e1eb9-4eef-4696-acac-67dc64e24804', 'b538da8e-450c-4b69-a661-58b82b64dd17', 2, 'decided', 'Budget set at $100–130K');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('b72ab2c5-089e-48ba-a473-01c96bf4caf9', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'call', '2026-09-05T12:00:00Z', 'First call', 'Call · 45 min');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('ff690e05-99e7-4eb6-acdd-d79076e7f19f', 'b72ab2c5-089e-48ba-a473-01c96bf4caf9', 'b538da8e-450c-4b69-a661-58b82b64dd17', 0, 'decided', 'Two tentpole streams anchor the flight');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('be67afe9-dc01-432d-ae34-c89da5971413', 'b72ab2c5-089e-48ba-a473-01c96bf4caf9', 'b538da8e-450c-4b69-a661-58b82b64dd17', 1, 'changed', 'TikTok moved to a secondary channel');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('fc1bff48-95a6-4c6f-a612-9339d77687d6', 'b72ab2c5-089e-48ba-a473-01c96bf4caf9', null, 2, 'next', 'First proposal by Sep 9');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('fd3bd995-ce02-46cf-a093-107de7c641f3', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'document', '2026-09-09T12:00:00Z', 'Proposal v1 shared', 'Document');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('36bf4d14-b6f7-47e5-a41e-715c24e950eb', 'fd3bd995-ce02-46cf-a093-107de7c641f3', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 0, 'new', 'v1: 14 creators, three tiers, $128K');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'email', '2026-09-16T12:00:00Z', 'Feedback on v2', 'Email · 4 messages');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('c675204a-020a-43b5-a3e4-ab1047b823bd', '6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 0, 'changed', 'Tier 1 cut from four creators to three');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('293498f9-4d76-4abb-a82d-8f3fcd638dcc', '6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 1, 'changed', 'Flight extended through August');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('aacec9d6-1ec7-4315-a6ec-4d6d34805f05', '6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', '0871ee31-b137-422f-a3fe-34973e716340', 2, 'changed', 'One Tier 1 creator to be dropped');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('84a53ec0-4004-4d3e-ae89-3b9733e729a9', '6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', null, 3, 'next', 'Revised proposal by Sep 22');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('f9acebd1-da4b-4798-ab8a-54c51b627c9c', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'document', '2026-09-22T12:00:00Z', 'Proposal v3 shared', 'Document');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('07849842-7367-4187-afb7-74a66f7a027d', 'f9acebd1-da4b-4798-ab8a-54c51b627c9c', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 0, 'new', 'v3: 12 creators, total down to $120K');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('719194c6-d577-4d66-afa0-4a2c12b2e6d3', 'f9acebd1-da4b-4798-ab8a-54c51b627c9c', '0871ee31-b137-422f-a3fe-34973e716340', 1, 'new', 'v2: twelve selected, two alternates per tier');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('9739fed3-e9b4-4470-ace1-397923b9ad39', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'call', '2026-09-25T12:00:00Z', 'Proposal walkthrough', 'Call · 35 min');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('55e9cb09-53eb-479f-aaf2-99f0ba5b4b56', '9739fed3-e9b4-4470-ace1-397923b9ad39', '403f455b-fc81-4eb3-a000-e59422a4d94b', 0, 'new', 'Walkthrough slides shared after the call');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('36668646-6c23-4ea1-a4af-234ffc4c10a4', '9739fed3-e9b4-4470-ace1-397923b9ad39', '0871ee31-b137-422f-a3fe-34973e716340', 1, 'asked', 'Swap one Tier 2 creator');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('e4c10931-100c-4d04-ab36-bc19ef326753', '9739fed3-e9b4-4470-ace1-397923b9ad39', null, 2, 'asked', 'How Arcadia Pass trials are measured');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('8bcb7b6d-9549-4782-add1-8d27f9cdd45d', '9739fed3-e9b4-4470-ace1-397923b9ad39', null, 3, 'next', 'Measurement plan Sep 26');
insert into timeline_moments (id, space_id, kind, occurred_at, title, meta) values ('a4179825-2dc0-4ca9-a5e3-2b2be792ada4', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'pending', '2026-10-06T12:00:00Z', 'Your feedback on tiers', 'Due');
insert into moment_changes (id, moment_id, document_id, position, kind, body) values ('c0a9108b-bfcb-497a-a161-e7e2cd8e92ee', 'a4179825-2dc0-4ca9-a5e3-2b2be792ada4', '2c1c1042-8ba0-4f16-a4a1-ba824f3c1876', 0, 'next', 'Your consolidated feedback on the tiers');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('c94c43c1-4f98-427a-aa94-180412bcb5a7', '7f82b744-7a58-45fc-a9ec-a31812007c15', '7d1038d4-724d-47b3-a846-07a2a431e7ec', 'email', '2026-08-26T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '38c01502-185e-4fa5-a2e8-5a340938324e']::uuid[], 'Creator program idea', 'Northlight pitched a summer creator program for Arcadia Pass.', '2 messages', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('32f26700-a83a-475f-a2fc-ae774e9ad3af', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'fa6e1eb9-4eef-4696-acac-67dc64e24804', 'email', '2026-09-02T12:00:00Z', array['38c01502-185e-4fa5-a2e8-5a340938324e', 'c7d101c1-c7ef-499e-aad1-8119d32954ec']::uuid[], 'Brief received', 'Summer brief shared with a $100–130K budget.', '1 message', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('36df99e9-018b-45ef-a819-08b47e6310df', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'b72ab2c5-089e-48ba-a473-01c96bf4caf9', 'call', '2026-09-05T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '23d902de-defe-46ba-ab91-8dc99bf95eea', '38c01502-185e-4fa5-a2e8-5a340938324e', '36eb0377-0ada-4ac6-ae6f-2843a6138418']::uuid[], 'First call', 'Agreed two tentpole streams; TikTok moved to secondary.', '45 min', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('350f089e-c89e-47f0-a58b-04e65ded4806', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'fd3bd995-ce02-46cf-a093-107de7c641f3', 'email', '2026-09-09T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '38c01502-185e-4fa5-a2e8-5a340938324e']::uuid[], 'Proposal v1 sent', 'Fourteen creators across three tiers at $128K.', '1 message', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('4083c92d-e641-40c0-a83e-b2a9531048cd', '7f82b744-7a58-45fc-a9ec-a31812007c15', '6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', 'email', '2026-09-15T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '38c01502-185e-4fa5-a2e8-5a340938324e']::uuid[], 'Proposal v2 sent', 'Thirteen creators over June and July at $124K.', '1 message', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('4bd66d30-7dd2-42d4-a0cd-d81102916fef', '7f82b744-7a58-45fc-a9ec-a31812007c15', '6eae54bd-cdcc-4f89-a6c5-abdc8ba9fc90', 'email', '2026-09-16T12:00:00Z', array['38c01502-185e-4fa5-a2e8-5a340938324e', '36eb0377-0ada-4ac6-ae6f-2843a6138418', 'c7d101c1-c7ef-499e-aad1-8119d32954ec']::uuid[], 'Feedback on v2', 'Fewer Tier 1 creators and a longer flight requested.', '4 messages', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('4b527cca-b459-4dbf-a6f1-276d6638469b', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'f9acebd1-da4b-4798-ab8a-54c51b627c9c', 'email', '2026-09-22T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '38c01502-185e-4fa5-a2e8-5a340938324e']::uuid[], 'Proposal v3 sent', 'Tier 1 reduced to three; flight extended through August.', '1 message', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('7fdf5408-861d-41e8-a6ed-1a2f458a240a', '7f82b744-7a58-45fc-a9ec-a31812007c15', '9739fed3-e9b4-4470-ace1-397923b9ad39', 'call', '2026-09-25T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '23d902de-defe-46ba-ab91-8dc99bf95eea', '38c01502-185e-4fa5-a2e8-5a340938324e', '36eb0377-0ada-4ac6-ae6f-2843a6138418']::uuid[], 'Proposal walkthrough', 'Asked about swapping one Tier 2 creator and trial measurement.', '35 min', 'approved');
insert into correspondence_entries (id, space_id, moment_id, kind, occurred_at, participant_ids, subject, summary, meta, review_status) values ('1bfe2c88-5314-4e95-a91b-10331096b771', '7f82b744-7a58-45fc-a9ec-a31812007c15', 'a4179825-2dc0-4ca9-a5e3-2b2be792ada4', 'email', '2026-09-30T12:00:00Z', array['c7d101c1-c7ef-499e-aad1-8119d32954ec', '38c01502-185e-4fa5-a2e8-5a340938324e']::uuid[], 'Follow-up on tier feedback', 'Alex confirmed consolidated comments by Oct 6.', '3 messages', 'approved');
commit;
