// Seed fixture: Microsoft · Xbox — Summer Creator Package ($120K), sold by
// a Northlight-style seller team. This is the single source of truth for
// demo data: the UI renders from it when Supabase isn't configured, and
// scripts/gen-seed-sql.ts turns it into supabase/seed.sql.
//
// Must stay free of runtime imports so Node can run the generator directly.

import type { ClientSpaceView } from "../domain/types";

const SPACE = "spc_xbox_summer";
const DEAL = "deal_xbox_summer";
const ACCOUNT = "acct_xbox";

export const DEMO_LINK_TOKEN = "demo-xbox-summer";

export const fixture: ClientSpaceView = {
  org: { id: "org_northlight", name: "Northlight", slug: "northlight" },
  account: {
    id: ACCOUNT,
    orgId: "org_northlight",
    name: "Microsoft · Xbox",
    parentName: "Microsoft",
    logoText: "X",
    logoColor: "#107c10",
  },
  deal: {
    id: DEAL,
    accountId: ACCOUNT,
    name: "Summer Creator Package",
    stage: "revisions",
    value: { amount: 120000, currency: "USD" },
    brief: {
      budget: { amount: 120000, currency: "USD" },
      audience: "Core and lapsed gamers, 18–34, US & UK",
      platforms: ["YouTube", "TikTok", "Twitch"],
      flight: { start: "2027-06-07", end: "2027-08-29" },
      deliverables: [
        "6 creator integrations",
        "3 live streams",
        "Paid amplification of top-performing cuts",
      ],
      measurement: ["Reach", "Completed views", "Game Pass sign-up lift"],
    },
  },
  space: {
    id: SPACE,
    dealId: DEAL,
    initiator: "seller",
    statusLabel: "Awaiting your feedback",
    statusDueDate: "2026-10-06",
    readOnly: false,
  },
  people: [
    {
      id: "p_maya",
      name: "Maya Chen",
      email: "maya.chen@xbox.example",
      title: "Brand Manager, Game Pass",
      company: "Microsoft · Xbox",
      side: "buyer",
      avatarColor: "#5b7c99",
      membership: {
        personId: "p_maya",
        scope: "account",
        scopeId: ACCOUNT,
        side: "buyer",
        presence: { kind: "viewing" },
      },
    },
    {
      id: "p_jordan",
      name: "Jordan Ellis",
      email: "jordan@wavelength.example",
      title: "Media Lead, Wavelength",
      company: "Wavelength Media",
      side: "buyer",
      avatarColor: "#a0785a",
      membership: {
        personId: "p_jordan",
        scope: "deal",
        scopeId: DEAL,
        side: "buyer",
        presence: { kind: "seen", at: "2026-09-30T16:20:00Z" },
      },
    },
    {
      id: "p_priya",
      name: "Priya Nair",
      email: "priya@wavelength.example",
      title: "Planner, Wavelength",
      company: "Wavelength Media",
      side: "buyer",
      avatarColor: "#8a7aa8",
      membership: {
        personId: "p_priya",
        scope: "deal",
        scopeId: DEAL,
        side: "buyer",
        presence: { kind: "invited", at: "2026-10-01T09:00:00Z" },
      },
    },
    {
      id: "p_sam",
      name: "Sam Whitaker",
      email: "sam@northlight.example",
      title: "Partnerships Director",
      company: "Northlight",
      side: "seller",
      avatarColor: "#1f6f4a",
      membership: {
        personId: "p_sam",
        scope: "deal",
        scopeId: DEAL,
        side: "seller",
        presence: { kind: "seen", at: "2026-10-02T08:45:00Z" },
      },
    },
    {
      id: "p_alex",
      name: "Alex Rivera",
      email: "alex@northlight.example",
      title: "Creator Partnerships",
      company: "Northlight",
      side: "seller",
      avatarColor: "#c06a4a",
      membership: {
        personId: "p_alex",
        scope: "deal",
        scopeId: DEAL,
        side: "seller",
        presence: { kind: "seen", at: "2026-09-30T11:10:00Z" },
      },
    },
    {
      id: "p_lena",
      name: "Lena Okafor",
      email: "lena@northlight.example",
      title: "Head of Marketing",
      company: "Northlight",
      side: "seller",
      avatarColor: "#3d6b78",
      membership: {
        personId: "p_lena",
        scope: "account",
        scopeId: ACCOUNT,
        side: "seller",
        presence: { kind: "seen", at: "2026-09-26T15:00:00Z" },
      },
    },
  ],
  documents: [
    {
      id: "doc_proposal",
      spaceId: SPACE,
      title: "Summer Creator Package — Proposal",
      kind: "deck",
      source: "google_drive",
      pinned: true,
      versions: [
        {
          id: "ver_proposal_1",
          documentId: "doc_proposal",
          number: 1,
          committedAt: "2026-09-18T14:00:00Z",
          sharedByPersonId: "p_sam",
          summary: "Five creators across YouTube and Twitch, eight-week flight.",
          pageCount: 14,
          sections: [
            { id: "s_p1_overview", heading: "Overview", page: 2, text: "A summer creator programme for Game Pass built around five Northlight creators on YouTube and Twitch over an eight-week flight from late June." },
            { id: "s_p1_creators", heading: "Creator lineup", page: 5, text: "Five creators: two variety streamers, two shooter specialists and one cozy-games creator, with combined reach of 18M." },
            { id: "s_p1_investment", heading: "Investment", page: 12, text: "Total investment $120,000 covering creator fees, production and $20,000 paid amplification." },
          ],
        },
        {
          id: "ver_proposal_2",
          documentId: "doc_proposal",
          number: 2,
          committedAt: "2026-09-30T15:30:00Z",
          sharedByPersonId: "p_sam",
          summary: "Six creators, TikTok added, flight moved to June 7 – Aug 29.",
          pageCount: 16,
          sections: [
            { id: "s_p2_overview", heading: "Overview", page: 2, text: "A summer creator programme for Game Pass with six creators across YouTube, TikTok and Twitch, running June 7 to August 29, 2027." },
            { id: "s_p2_creators", heading: "Creator lineup", page: 5, text: "Six creators: one shooter specialist was swapped for a TikTok-first creator and a second cozy-games creator added. Combined reach 24M." },
            { id: "s_p2_streams", heading: "Live streams", page: 9, text: "Three sponsored live streams timed to the June showcase, mid-July, and the August content drop." },
            { id: "s_p2_investment", heading: "Investment", page: 14, text: "Total investment remains $120,000. Paid amplification reduced to $15,000 to fund the sixth creator." },
          ],
        },
      ],
    },
    {
      id: "doc_media_plan",
      spaceId: SPACE,
      title: "Media plan & flighting",
      kind: "sheet",
      source: "google_drive",
      pinned: false,
      versions: [
        {
          id: "ver_plan_1",
          documentId: "doc_media_plan",
          number: 1,
          committedAt: "2026-09-18T14:05:00Z",
          sharedByPersonId: "p_alex",
          summary: "Week-by-week flighting for five creators.",
          pageCount: 3,
          sections: [
            { id: "s_m1_flight", heading: "Flighting", page: 1, text: "Eight weeks from June 28. Two creator drops per week in weeks 1–4, one per week thereafter." },
          ],
        },
        {
          id: "ver_plan_2",
          documentId: "doc_media_plan",
          number: 2,
          committedAt: "2026-09-30T15:35:00Z",
          sharedByPersonId: "p_alex",
          summary: "Twelve-week flight with TikTok bursts around live streams.",
          pageCount: 4,
          sections: [
            { id: "s_m2_flight", heading: "Flighting", page: 1, text: "Twelve weeks from June 7 to August 29. TikTok bursts in the 48 hours around each live stream." },
            { id: "s_m2_paid", heading: "Paid amplification", page: 3, text: "$15,000 paid amplification on the top two performing cuts, decided at week 3." },
          ],
        },
      ],
    },
    {
      id: "doc_brief",
      spaceId: SPACE,
      title: "Xbox Summer 2027 — Brief",
      kind: "doc",
      source: "upload",
      pinned: false,
      versions: [
        {
          id: "ver_brief_1",
          documentId: "doc_brief",
          number: 1,
          committedAt: "2026-09-08T10:00:00Z",
          sharedByPersonId: "p_maya",
          summary: "Drive Game Pass sign-ups with lapsed 18–34 players.",
          pageCount: 4,
          sections: [
            { id: "s_b1_objective", heading: "Objective", page: 1, text: "Drive Game Pass sign-ups among core and lapsed gamers aged 18–34 in the US and UK over summer 2027." },
            { id: "s_b1_budget", heading: "Budget", page: 3, text: "Working budget of $120,000 inclusive of production and paid support." },
          ],
        },
      ],
    },
    {
      id: "doc_rate_card",
      spaceId: SPACE,
      title: "Creator rate card 2027",
      kind: "pdf",
      source: "upload",
      pinned: false,
      versions: [
        {
          id: "ver_rate_1",
          documentId: "doc_rate_card",
          number: 1,
          committedAt: "2026-09-12T17:00:00Z",
          sharedByPersonId: "p_sam",
          summary: "Integration, stream and usage-rights pricing.",
          pageCount: 2,
          sections: [
            { id: "s_r1_rates", heading: "Rates", page: 1, text: "Dedicated integrations from $9,000; sponsored live streams from $6,500; 90-day paid usage rights at 20% of fee." },
          ],
        },
      ],
    },
    {
      id: "doc_shortlist",
      spaceId: SPACE,
      title: "Creator shortlist",
      kind: "sheet",
      source: "google_drive",
      pinned: false,
      versions: [
        {
          id: "ver_short_1",
          documentId: "doc_shortlist",
          number: 1,
          committedAt: "2026-09-30T15:40:00Z",
          sharedByPersonId: "p_alex",
          summary: "Six confirmed creators plus two alternates.",
          pageCount: 2,
          sections: [
            { id: "s_s1_list", heading: "Shortlist", page: 1, text: "Six confirmed creators with audience splits; two alternates held for the TikTok slot if availability changes." },
          ],
        },
      ],
    },
    {
      id: "doc_measurement",
      spaceId: SPACE,
      title: "Measurement framework",
      kind: "doc",
      source: "google_drive",
      pinned: false,
      versions: [
        {
          id: "ver_meas_1",
          documentId: "doc_measurement",
          number: 1,
          committedAt: "2026-09-30T15:45:00Z",
          sharedByPersonId: "p_lena",
          summary: "Reach, completed views, and Game Pass sign-up lift study.",
          pageCount: 3,
          sections: [
            { id: "s_me1_kpis", heading: "KPIs", page: 1, text: "Primary KPI is Game Pass sign-up lift measured via a holdout study; secondary KPIs are reach and completed views." },
          ],
        },
      ],
    },
  ],
  moments: [
    {
      id: "m_brief",
      spaceId: SPACE,
      kind: "email",
      occurredAt: "2026-09-08T10:00:00Z",
      title: "Brief received",
      summary: "Maya shared the Summer 2027 brief: Game Pass sign-ups, 18–34, $120K working budget.",
      changes: [
        { documentId: "doc_brief", kind: "new", text: "Brief shared by Xbox." },
      ],
    },
    {
      id: "m_kickoff",
      spaceId: SPACE,
      kind: "call",
      occurredAt: "2026-09-12T16:00:00Z",
      title: "Kickoff call",
      summary: "Aligned on objectives and the $120K budget. Northlight shared its 2027 rate card.",
      changes: [
        { documentId: "doc_brief", kind: "decided", text: "Budget confirmed at $120K all-in." },
        { documentId: "doc_rate_card", kind: "new", text: "2027 rate card shared." },
      ],
    },
    {
      id: "m_proposal_v1",
      spaceId: SPACE,
      kind: "document",
      occurredAt: "2026-09-18T14:00:00Z",
      title: "Proposal v1 shared",
      summary: "First proposal and media plan: five creators on YouTube and Twitch over eight weeks.",
      changes: [
        { documentId: "doc_proposal", kind: "new", text: "Five creators, YouTube and Twitch." },
        { documentId: "doc_media_plan", kind: "new", text: "Eight-week flight from June 28." },
      ],
    },
    {
      id: "m_feedback",
      spaceId: SPACE,
      kind: "email",
      occurredAt: "2026-09-23T09:30:00Z",
      title: "Feedback on v1",
      summary: "Jordan asked to add TikTok, swap one shooter creator, and start the flight earlier in June.",
      changes: [],
    },
    {
      id: "m_revisions_call",
      spaceId: SPACE,
      kind: "call",
      occurredAt: "2026-09-26T15:00:00Z",
      title: "Revisions call",
      summary: "Agreed six creators across three platforms, a June 7 start, and keeping the budget flat.",
      changes: [
        { documentId: "doc_proposal", kind: "decided", text: "Six creators across YouTube, TikTok and Twitch." },
        { documentId: "doc_media_plan", kind: "decided", text: "Flight runs June 7 – Aug 29." },
      ],
    },
    {
      id: "m_proposal_v2",
      spaceId: SPACE,
      kind: "document",
      occurredAt: "2026-09-30T15:30:00Z",
      title: "Proposal v2 shared",
      summary: "Revised proposal, plan, creator shortlist and measurement framework reflecting the revisions call.",
      changes: [
        { documentId: "doc_proposal", kind: "changed", text: "Sixth creator added; paid amplification cut to $15K." },
        { documentId: "doc_media_plan", kind: "changed", text: "Twelve-week flight with TikTok bursts." },
        { documentId: "doc_shortlist", kind: "new", text: "Six creators plus two alternates." },
        { documentId: "doc_measurement", kind: "new", text: "Sign-up lift holdout study." },
      ],
    },
    {
      id: "m_pending",
      spaceId: SPACE,
      kind: "pending",
      occurredAt: "2026-10-06T17:00:00Z",
      title: "Your feedback on v2",
      summary: "Sign-off on the creator lineup and flight so contracting can start.",
      changes: [],
    },
  ],
  correspondence: [
    {
      id: "c_brief",
      spaceId: SPACE,
      momentId: "m_brief",
      kind: "email",
      occurredAt: "2026-09-08T10:00:00Z",
      authorPersonId: "p_maya",
      subject: "Summer 2027 creator brief",
      summary: "Shared the brief. Priority is Game Pass sign-ups among lapsed players; open to platform recommendations.",
      reviewStatus: "approved",
    },
    {
      id: "c_kickoff",
      spaceId: SPACE,
      momentId: "m_kickoff",
      kind: "call",
      occurredAt: "2026-09-12T16:00:00Z",
      authorPersonId: "p_sam",
      subject: "Kickoff call notes",
      summary: "Confirmed $120K all-in. Xbox prefers creators with existing Game Pass affinity. Proposal due Sep 18.",
      reviewStatus: "approved",
    },
    {
      id: "c_v1_sent",
      spaceId: SPACE,
      momentId: "m_proposal_v1",
      kind: "email",
      occurredAt: "2026-09-18T14:00:00Z",
      authorPersonId: "p_sam",
      subject: "Proposal v1",
      summary: "Sent the first proposal and media plan for review.",
      reviewStatus: "approved",
    },
    {
      id: "c_feedback",
      spaceId: SPACE,
      momentId: "m_feedback",
      kind: "email",
      occurredAt: "2026-09-23T09:30:00Z",
      authorPersonId: "p_jordan",
      subject: "Re: Proposal v1",
      summary: "Requested TikTok coverage, swapping one shooter creator, and an early-June start to catch the showcase.",
      reviewStatus: "approved",
    },
    {
      id: "c_revisions",
      spaceId: SPACE,
      momentId: "m_revisions_call",
      kind: "call",
      occurredAt: "2026-09-26T15:00:00Z",
      authorPersonId: "p_alex",
      subject: "Revisions call notes",
      summary: "Agreed six creators and a June 7 start. Budget stays at $120K by trimming paid amplification.",
      reviewStatus: "approved",
    },
    {
      id: "c_v2_sent",
      spaceId: SPACE,
      momentId: "m_proposal_v2",
      kind: "email",
      occurredAt: "2026-09-30T15:30:00Z",
      authorPersonId: "p_sam",
      subject: "Proposal v2 + shortlist",
      summary: "Shared v2 with the shortlist and measurement framework. Asked for feedback by Oct 6.",
      reviewStatus: "approved",
    },
  ],
};
