// Generates supabase/seed.sql from src/lib/seed/fixture.ts.
// Run with: npm run seed:gen   (Node ≥ 22.18 strips TS types natively)

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { DEMO_LINK_TOKEN, fixture } from "../src/lib/seed/fixture.ts";

// Deterministic UUIDs from fixture ids so re-seeding is stable.
const uuid = (id: string) => {
  const h = createHash("sha256").update(`atria:${id}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const insert = (table: string, row: Record<string, unknown>) =>
  `insert into ${table} (${Object.keys(row).join(", ")}) values (${Object.values(row).map(q).join(", ")});`;

const f = fixture;
const orgId = uuid(f.org.id);
const out: string[] = [
  "-- Generated by scripts/gen-seed-sql.ts from src/lib/seed/fixture.ts. Do not edit by hand.",
  "begin;",
  insert("orgs", { id: orgId, name: f.org.name, slug: f.org.slug }),
  insert("accounts", {
    id: uuid(f.account.id), org_id: orgId, name: f.account.name,
    parent_name: f.account.parentName, logo_text: f.account.logoText, logo_color: f.account.logoColor,
  }),
  // Insert at the final stage directly; the trigger only guards updates.
  insert("deals", {
    id: uuid(f.deal.id), org_id: orgId, account_id: uuid(f.account.id), name: f.deal.name,
    stage: f.deal.stage, value_amount: f.deal.value?.amount, value_currency: f.deal.value?.currency,
  }),
];

const b = f.deal.brief;
if (b) {
  out.push(insert("deal_briefs", {
    deal_id: uuid(f.deal.id), budget_amount: b.budget?.amount, budget_currency: b.budget?.currency,
    audience: b.audience, platforms: b.platforms ?? [], flight_start: b.flight?.start, flight_end: b.flight?.end,
    deliverables: b.deliverables ?? [], measurement: b.measurement ?? [],
  }));
}

out.push(insert("spaces", {
  id: uuid(f.space.id), org_id: orgId, deal_id: uuid(f.deal.id), initiator: f.space.initiator,
  status_label: f.space.statusLabel, status_due_date: f.space.statusDueDate,
}));

out.push(insert("space_links", {
  id: uuid("link_demo"), space_id: uuid(f.space.id),
  token_hash: createHash("sha256").update(DEMO_LINK_TOKEN).digest("hex"),
}));

for (const p of f.people) {
  out.push(insert("people", {
    id: uuid(p.id), org_id: orgId, name: p.name, email: p.email, title: p.title,
    company: p.company, side: p.side, avatar_color: p.avatarColor,
  }));
  const m = p.membership;
  const pres = m.presence;
  out.push(insert("memberships", {
    id: uuid(`mem_${p.id}`), org_id: orgId, person_id: uuid(p.id), scope: m.scope,
    account_id: m.scope === "account" ? uuid(m.scopeId) : null,
    deal_id: m.scope === "deal" ? uuid(m.scopeId) : null,
    side: m.side,
    invited_at: pres.kind === "invited" ? pres.at : "2026-09-08T10:00:00Z",
    last_seen_at: pres.kind === "seen" ? pres.at : null,
  }));
}

for (const d of f.documents) {
  out.push(insert("documents", {
    id: uuid(d.id), space_id: uuid(f.space.id), title: d.title, kind: d.kind, source: d.source, pinned: d.pinned,
  }));
  for (const v of d.versions) {
    out.push(insert("document_versions", {
      id: uuid(v.id), document_id: uuid(d.id), number: v.number, committed_at: v.committedAt,
      shared_by: uuid(v.sharedByPersonId), summary: v.summary, page_count: v.pageCount, shared: true,
      extracted_text: v.sections.map((s) => `${s.heading}\n${s.text}`).join("\n\n"),
    }));
    v.sections.forEach((s, i) =>
      out.push(insert("document_sections", {
        id: uuid(s.id), version_id: uuid(v.id), position: i, heading: s.heading, page: s.page, body: s.text,
      })),
    );
  }
}

for (const m of f.moments) {
  out.push(insert("timeline_moments", {
    id: uuid(m.id), space_id: uuid(f.space.id), kind: m.kind, occurred_at: m.occurredAt, title: m.title, summary: m.summary,
  }));
  m.changes.forEach((c, i) =>
    out.push(insert("moment_changes", {
      id: uuid(`${m.id}_${i}`), moment_id: uuid(m.id), document_id: uuid(c.documentId), position: i, kind: c.kind, body: c.text,
    })),
  );
}

for (const c of f.correspondence) {
  out.push(insert("correspondence_entries", {
    id: uuid(c.id), space_id: uuid(f.space.id), moment_id: c.momentId ? uuid(c.momentId) : null, kind: c.kind,
    occurred_at: c.occurredAt, author_id: uuid(c.authorPersonId), subject: c.subject, summary: c.summary,
    review_status: c.reviewStatus,
  }));
}

out.push("commit;", "");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log(`Wrote supabase/seed.sql (${out.length} statements)`);
